export const TRAER_TODOS = 'TRAER_TODOS';
export const CARGANDO    = 'CARGANDO ';
export const LIMPIAR     = 'LIMPIAR ';
export const ACTUALIZAR_LISTADO = 'ACTUALIZAR_LISTADO';
export const ACTUALIZAR_USER_INFO = "ACTUALIZAR_USER_INFO";